# Generated by Django 5.2.3 on 2025-07-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='alert_type',
            field=models.CharField(choices=[('medical', 'Medical'), ('threat', 'Threat'), ('accident', 'Accident'), ('lost', 'Lost'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
