# Generated by Django 5.2.3 on 2025-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver’s License'), ('other', 'Other')], default='passport', max_length=50),
        ),
    ]
