# Generated by Django 5.2.3 on 2025-06-29 18:10

import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kyc_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='id_document_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_document_file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie_file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/documents/', validators=[kyc.models.validate_file_pdf_only]),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/', validators=[kyc.models.validate_image_size]),
        ),
    ]
