# Generated by Django 5.2.3 on 2025-07-06 14:13

import cloudinary.models
import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_remove_kyc_id_document_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='id_document_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_document_file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver’s License'), ('other', 'Other')], default='passport', max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='selfie_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[kyc.models.validate_image_size]),
        ),
    ]
